In [1]:
import cv2
import numpy as np

In [2]:
# Init Camera
cap = cv2.VideoCapture(0)

# Face Detection
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_alt.xml")
dataset_path = './Data/'
skip = 0
face_data = []
file_name = input("Enter the name of Person: ")


while True:
    ret, frame = cap.read()
    gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(frame,1.3,5)
    faces = sorted(faces,key=lambda f:f[2]*f[3])
    #print(len(faces))
    
    # Pick the last face (bcz it is largest acc to area: Area = f[2]*f[3])
    for (x,y,w,h) in faces[-1:]:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
        
        # Extract (Crop out required face) : Region of Interest
        offset = 10
        face_section = frame[y-offset:y+h+offset, x-offset:x+w+offset]
        face_section = cv2.resize(face_section,(100,100))
        
        skip+=1
        if skip%10==0:
            face_data.append(face_section)
            #print("Face Data Len: ",len(face_data))
            #print("SKIP: ",skip)
        
        cv2.imshow("Face Section",face_section)

        
    
    if ret == False:
        continue
        
    cv2.imshow("Video Frame",frame)
    
    # Store every 10th Face
    if skip%10==0:
        pass
    
    # Exiting Code
    key_pressed = cv2.waitKey(1) & 0xFF
    x = cv2.waitKey(1)
    if key_pressed == ord('q'):
        break
        
# Convert face list in numpy array
#print("before np.array",face_data)
print("before np.array",len(face_data))
face_data = np.array(face_data)
print("after np.array",face_data)
print("after np.array",face_data.shape)
face_data = face_data.reshape((face_data.shape[0],-1))
print('after reshape',face_data)
print('after reshape',face_data.shape)

# Save this data into file system
np.save(dataset_path+file_name+".npy",face_data)
print("Data Successfully Saved at ",dataset_path+file_name+".npy")


cap.release()
cv2.destroyAllWindows()

Enter the name of Person: Anup
before np.array 9
after np.array [[[[175 180 187]
   [174 179 186]
   [174 179 186]
   ...
   [142 137 146]
   [168 166 175]
   [167 169 178]]

  [[174 174 182]
   [177 178 186]
   [178 181 188]
   ...
   [134 133 139]
   [155 155 161]
   [159 160 166]]

  [[172 170 178]
   [176 176 184]
   [176 179 186]
   ...
   [139 138 142]
   [168 169 173]
   [174 175 179]]

  ...

  [[  4 121 167]
   [  1 134 181]
   [  0 136 185]
   ...
   [ 60  55  49]
   [ 75  69  63]
   [ 85  81  74]]

  [[ 10 122 169]
   [  0 123 171]
   [  0 141 188]
   ...
   [ 73  72  66]
   [ 65  65  57]
   [ 76  76  68]]

  [[  7 110 156]
   [  2 128 174]
   [  5 142 189]
   ...
   [ 78  76  68]
   [ 53  51  43]
   [ 65  63  54]]]


 [[[171 171 179]
   [170 173 180]
   [170 173 180]
   ...
   [127 133 135]
   [151 157 160]
   [163 166 172]]

  [[170 170 178]
   [171 171 179]
   [171 171 179]
   ...
   [123 134 132]
   [150 159 161]
   [151 160 164]]

  [[168 168 176]
   [174 172 179]
   [1